// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aypphmqberpvasfpszrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cHBobXFiZXJwdmFzZnBzenJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1Njk1ODUsImV4cCI6MjA2MDE0NTU4NX0.hWbO6wOw3B_-4buXpbZKF1WpSjeDje-ODJfVRoLMARU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);